import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'html',
      value: '<h3>Introduction</h3>',
      className: 'sidebar-heading',
    },
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'html',
      value: '<h3>Мультимарочные</h3>',
      className: 'sidebar-heading',
    },
    {
      type: 'category',
      label: 'Autocom',
      items: [
        {
          type: 'autogenerated',
          dirName: 'autocom',
        },
      ],
    },
    {
      type: 'category',
      label: 'Delphi',
      items: [
        {
          type: 'autogenerated',
          dirName: 'delphi',
        },
      ],
    },
    {
      type: 'category',
      label: 'Mucar/Thinkcar/Thinkdiag',
      items: [
        {
          type: 'autogenerated',
          dirName: 'mucar-thinkdiag',
        },
      ],
    },
    {
      type: 'category',
      label: 'Wurth WoW',
      items: [
        {
          type: 'autogenerated',
          dirName: 'wow',
        },
      ],
    },
    {
      type: 'html',
      value: '<h3>API Reference</h3>',
      className: 'sidebar-heading',
    },
    {type: 'autogenerated', dirName: 'delphi'},
  ],
};

export default sidebars;
