import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Вступление',
      items: [
        'intro',
      ],
    },
    {
      type: 'category',
      label: 'Мультимарочные',
      items: [
        {
          type: 'category',
          label: 'Autocom',
          items: [
            {
              type: 'autogenerated',
              dirName: 'autocom',
            },
          ],
        },
        {
          type: 'category',
          label: 'Delphi',
          items: [
            {
              type: 'autogenerated',
              dirName: 'delphi',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Марочные',
      items: [
        {
          type: 'category',
          label: 'Wow',
          items: [
            {
              type: 'autogenerated',
              dirName: 'wow',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
